name: PHPCS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validar composer.json e composer.lock
        run: ls -la
        run: cd petshopMentoria
        run: composer validate --strict
        run: ls -la

      # - name: Verificar erro de sintaxe
      #   run: php -l petshopMentoria/app/

      # - name: Instalar PHPCS
      #   run: |
      #       curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      #       php phpcs.phar --version
      #       php phpcs.phar --config-set default_standard PSR12
      #       php phpcs.phar petshopMentoria/app/

      # - name: PHP Code Style (phpcs)
      #   uses: chindit/actions-phpcs@master
      #   with:
      #     cli: --config-set default_standard PSR12
      #     # Folder to check code style
      #     dir: petshopMentoria/app/
